# Configuration for this blog
# it is written in Toml

[blog]
# What is your blog's name?
name = "Make Difference"
# What is your blog about?
description = "Here goes your blog's description" 
# your blog's url(ends without '/'), if you don't have one,  leave here blank
url = "http://lilac-less.hit9.org"
# which theme to use?
theme = "less"

[author]
name = "hit9"  # better be your github's username
email = "nz2324@126.com"  # your email address

[disqus]
# your disqus's short name for this blog
shortname = "followmyheart"
